apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app-hpa
  namespace: final
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app-deployment # Target the flask application deployment
  minReplicas: 1              # REQUIRED: Start with a minimum of 1 pod
  maxReplicas: 5              # Maximum number of pods to scale up to
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # REQUIRED: Target 50% CPU utilization